#!/bin/bash
#Compile tex file and get only pdf result
#By Dongjie Guo

texfile=$1
texonlyname=${texfile%.*}
latex $texfile
if test -f $texonlyname.dvi;then
    latex $texfile >/dev/null
    dvipdf $texonlyname.dvi
fi
if test -f $texonlyname.log;then
    rm $texonlyname.log
fi
if test -f $texonlyname.aux;then
    rm $texonlyname.aux
fi
if test -f $texonlyname.dvi;then
    rm $texonlyname.dvi
fi
