#!/bin/bash
#Compile tex file and get only pdf result
#By Dongjie Guo

texfile=$1
texonlyname=${texfile%.*}
if 
    xelatex $texonlyname
then
    printf 'xelatex command right.\n\n\n\n\n'
    bibtex $texonlyname
    xelatex $texonlyname >/dev/null
    xelatex $texonlyname >/dev/null
fi
rm $texonlyname.{log,aux}
if [ -f $texonlyname.bbl ];then
    rm $texonlyname.bbl
fi
if [ -f $texonlyname.blg ];then
    rm $texonlyname.blg
fi
declare -i aa=2
if [ $# -eq $aa ];then
    mv $texonlyname.pdf $2
fi
